quarkus:
  mongodb:
    connection-string:
      mongodb://localhost
    database: vbl
# Your configuration properties
  rest-client:
    m360-api:
      url: https://api.m360.com.ph/v3/api/broadcast
      scope: javax.inject.Singleton

ph:
  com:
    m360:
      api-key: 123456789
      api-secret: 123456789
      sender-id: ABCDE