quarkus:
  http:
    port: ${PORT:8080}
  mongodb:
    connection-string:
      ${MONGO_CONN_STRING:mongodb://localhost}
    database: vbl
# Your configuration properties
  rest-client:
    m360-api:
      url: https://api.m360.com.ph/v3/api/broadcast
      #url: https://localhost
      scope: javax.inject.Singleton
    gl-rewards-api:
      url: https://devapi.globelabs.com.ph/rewards/v1/transactions/send
      #url: https://localhost
      scope: javax.inject.Singleton
  oidc:
    auth-server-url: ${OIDC_AUTH_URL:https://localhost:8543/realms/quarkus}
    client-id: ${OIDC_CLIENT_ID:backend-api}
    credentials:
      secret: ${OIDC_SECRET:AABBCC}
    tls:
      verification: none
  keycloak:
    policy-enforcer:
      enable: true
      paths:
        '1':
          path: /fpi/login/*
          enforcement-mode: DISABLED
        '2':
          path: /fpi/sms/dlr/*
          enforcement-mode: DISABLED
        '3':
          path: /fpi/load/callback/*
          enforcement-mode: DISABLED
        '4':
          # debug
          path: /fpi/load/reload/*
          enforcement-mode: DISABLED

fpi:
  webhook:
    dlr:
      api-key: ${FPI_DLR_WEBHOOK_KEY:FPIDLRAABBBDDCCCQQQ}
    mo:
      api-key: ${FPI_MO_WEBHOOK_KEY:FPIDLRAABBBDDCCCQQQ}
    gen:
      api-key: ${FPI_GEN_WEBHOOK_KEY:FPIDLRAABBBDDCCCQQQ}

ph:
  com:
    m360:
      api-key: ${SMS_API_KEY:123456789}
      api-secret: ${SMS_SECRET:123456789}
      sender-id: ${SMS_SID:ABCDE}
    gl:
      app-id: ${GL_APP_ID:APP112233}
      app-secret: ${GL_APP_SEC:APPSEC112233}
      rewards:
        token: ${GL_APP_AMAX_TOKEN:APPSEC112233}

com:
  dtone:
    base-url: ${DTONE_BASEURL:https://preprod-dvs-api.dtone.com}
    api-key: ${DTONE_APIKEY:aaaaabbcccceee}
    api-secret: ${DTONE_APISECRET:zzzzxxeeedd}
