quarkus:
  http:
    port: ${PORT:8080}
  arc:
    exclude-types: com.abavilla.fpi.load.ext.rest.*
  mongodb:
    read-timeout: 120S
    connect-timeout: 120S
    server-selection-timeout: 120S
    connection-string:
      ${MONGO_CONN_STRING:mongodb://localhost}
    database: ${DB_NAME}
  liquibase-mongodb:
    migrate-at-start: true
    change-log: db/changeLog.xml
    validate-on-migrate: true
    clean-at-start: false
  rest-client:
    connect-timeout: 120000
    read-timeout: 120000
    gl-rewards-api:
      url: ${GL_REWARDS_API}
      scope: javax.inject.Singleton
    login-api:
      url: ${LOGIN_BASE_URI}
      scope: javax.inject.Singleton
    sms-api:
      url: ${SMS_BASE_URI}
      scope: javax.inject.Singleton
  oidc:
    auth-server-url: ${OIDC_AUTH_URL:https://localhost:8543/realms/quarkus}
    client-id: ${OIDC_CLIENT_ID:backend-api}
    credentials:
      secret: ${OIDC_SECRET:AABBCC}
    tls:
      verification: none
  keycloak:
    policy-enforcer:
      enable: true
      paths:
        '1':
          path: /fpi/load/callback/*
          enforcement-mode: DISABLED
#        '2':
#          # debug
#          path: /fpi/load/*
#          enforcement-mode: DISABLED
  native:
    resources:
      includes:
        com/google/i18n/phonenumbers/data/**,com/google/i18n/phonenumbers/carrier/data/**

fpi:
  app-to-app:
    auth:
      username: ${FPI_APP_TO_APP_USERN:username}
      password: ${FPI_APP_TO_APP_PASSW:password}
  webhook:
    gen:
      api-key: ${FPI_GEN_WEBHOOK_KEY:FPIDLRAABBBDDCCCQQQ}

ph:
  com:
    gl:
      app-id: ${GL_APP_ID:APP112233}
      app-secret: ${GL_APP_SEC:APPSEC112233}
      rewards:
        token: ${GL_APP_AMAX_TOKEN:APPSEC112233}

com:
  dtone:
    base-url: ${DTONE_BASEURL:https://preprod-dvs-api.dtone.com}
    api-key: ${DTONE_APIKEY:aaaaabbcccceee}
    api-secret: ${DTONE_APISECRET:zzzzxxeeedd}
    callback-url: ${DTONE_CALLBACK_URL:https://example.com}
